//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mze9412.ScriptCompiler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mze9412.ScriptCompiler.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space Engineers Script compiler (by mze9412).
        /// </summary>
        public static string Application_Name {
            get {
                return ResourceManager.GetString("Application_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy script to clipboard.
        /// </summary>
        public static string CopyScriptToClipboard_Title {
            get {
                return ResourceManager.GetString("CopyScriptToClipboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If checked the generated script will be copied into the clipboard for direct pasting into the game..
        /// </summary>
        public static string CopyScriptToClipboard_Tooltip {
            get {
                return ResourceManager.GetString("CopyScriptToClipboard_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile all.
        /// </summary>
        public static string DetectedScripts_CompileAll {
            get {
                return ResourceManager.GetString("DetectedScripts_CompileAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh scripts.
        /// </summary>
        public static string DetectedScripts_RefreshScripts {
            get {
                return ResourceManager.GetString("DetectedScripts_RefreshScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected scripts.
        /// </summary>
        public static string DetectedScripts_Title {
            get {
                return ResourceManager.GetString("DetectedScripts_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts Directory.
        /// </summary>
        public static string ScriptCodeDirectory_Title {
            get {
                return ResourceManager.GetString("ScriptCodeDirectory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the root directory of the scripts you want to compile..
        /// </summary>
        public static string ScriptCodeDirectory_Tooltip {
            get {
                return ResourceManager.GetString("ScriptCodeDirectory_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Directory.
        /// </summary>
        public static string ScriptOutputDirectory_Title {
            get {
                return ResourceManager.GetString("ScriptOutputDirectory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated scripts are deposited in this directory and can later be copied from there..
        /// </summary>
        public static string ScriptOutputDirectory_Tooltip {
            get {
                return ResourceManager.GetString("ScriptOutputDirectory_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select code directory.
        /// </summary>
        public static string SelectFolder_CodeDirectory {
            get {
                return ResourceManager.GetString("SelectFolder_CodeDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select output directory.
        /// </summary>
        public static string SelectFolder_OutputDirectory {
            get {
                return ResourceManager.GetString("SelectFolder_OutputDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
    }
}
